// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jRkyHyW5xUgunu5SjYQV4L
// Component: qBVjqzeCH3
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_doc_bundle.module.css"; // plasmic-import: jRkyHyW5xUgunu5SjYQV4L/projectcss
import sty from "./PlasmicColorPickerDot.module.css"; // plasmic-import: qBVjqzeCH3/css

export type PlasmicColorPickerDot__VariantMembers = {
  selected: "selected";
  color: "_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7";
  isSection: "isSection";
};

export type PlasmicColorPickerDot__VariantsArgs = {
  selected?: SingleBooleanChoiceArg<"selected">;
  color?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7">;
  isSection?: SingleBooleanChoiceArg<"isSection">;
};

type VariantPropType = keyof PlasmicColorPickerDot__VariantsArgs;
export const PlasmicColorPickerDot__VariantProps = new Array<VariantPropType>(
  "selected",
  "color",
  "isSection"
);

export type PlasmicColorPickerDot__ArgsType = {};
type ArgPropType = keyof PlasmicColorPickerDot__ArgsType;
export const PlasmicColorPickerDot__ArgProps = new Array<ArgPropType>();

export type PlasmicColorPickerDot__OverridesType = {
  root?: p.Flex<"button">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultColorPickerDotProps {
  selected?: SingleBooleanChoiceArg<"selected">;
  color?: SingleChoiceArg<"_1" | "_2" | "_3" | "_4" | "_5" | "_6" | "_7">;
  isSection?: SingleBooleanChoiceArg<"isSection">;
  className?: string;
}

function PlasmicColorPickerDot__RenderFunc(props: {
  variants: PlasmicColorPickerDot__VariantsArgs;
  args: PlasmicColorPickerDot__ArgsType;
  overrides: PlasmicColorPickerDot__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    true ? (
      <button
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.button,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root,
          {
            [sty.rootcolor__1]: hasVariant(variants, "color", "_1"),
            [sty.rootcolor__2]: hasVariant(variants, "color", "_2"),
            [sty.rootcolor__3]: hasVariant(variants, "color", "_3"),
            [sty.rootcolor__4]: hasVariant(variants, "color", "_4"),
            [sty.rootcolor__5]: hasVariant(variants, "color", "_5"),
            [sty.rootcolor__6]: hasVariant(variants, "color", "_6"),
            [sty.rootcolor__7]: hasVariant(variants, "color", "_7"),
            [sty.rootisSection]: hasVariant(variants, "isSection", "isSection"),
            [sty.rootselected]: hasVariant(variants, "selected", "selected")
          }
        )}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox, {
            [sty.freeBoxcolor__1]: hasVariant(variants, "color", "_1"),
            [sty.freeBoxcolor__2]: hasVariant(variants, "color", "_2"),
            [sty.freeBoxcolor__3]: hasVariant(variants, "color", "_3"),
            [sty.freeBoxcolor__4]: hasVariant(variants, "color", "_4"),
            [sty.freeBoxcolor__5]: hasVariant(variants, "color", "_5"),
            [sty.freeBoxcolor__6]: hasVariant(variants, "color", "_6"),
            [sty.freeBoxcolor__7]: hasVariant(variants, "color", "_7"),
            [sty.freeBoxisSection]: hasVariant(
              variants,
              "isSection",
              "isSection"
            ),
            [sty.freeBoxselected]: hasVariant(variants, "selected", "selected")
          })}
        />
      </button>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicColorPickerDot__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicColorPickerDot__VariantsArgs;
    args?: PlasmicColorPickerDot__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicColorPickerDot__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicColorPickerDot__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicColorPickerDot__ArgProps,
      internalVariantPropNames: PlasmicColorPickerDot__VariantProps
    });

    return PlasmicColorPickerDot__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicColorPickerDot";
  } else {
    func.displayName = `PlasmicColorPickerDot.${nodeName}`;
  }
  return func;
}

export const PlasmicColorPickerDot = Object.assign(
  // Top-level PlasmicColorPickerDot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicColorPickerDot
    internalVariantProps: PlasmicColorPickerDot__VariantProps,
    internalArgProps: PlasmicColorPickerDot__ArgProps
  }
);

export default PlasmicColorPickerDot;
/* prettier-ignore-end */
