// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jRkyHyW5xUgunu5SjYQV4L
// Component: sp9sQOJfZkb
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SideBarBookTitle from "../../SideBarBookTitle"; // plasmic-import: cpDlPT0ZyV/component
import { DragListView } from "../../../../../DragListView"; // plasmic-import: weFnPwWswI/codeComponent
import AddStock from "../../AddStock"; // plasmic-import: -k3H9wKgmJ/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_doc_bundle.module.css"; // plasmic-import: jRkyHyW5xUgunu5SjYQV4L/projectcss
import sty from "./PlasmicSideBarDocsAreaD.module.css"; // plasmic-import: sp9sQOJfZkb/css

export type PlasmicSideBarDocsAreaD__VariantMembers = {};

export type PlasmicSideBarDocsAreaD__VariantsArgs = {};
type VariantPropType = keyof PlasmicSideBarDocsAreaD__VariantsArgs;
export const PlasmicSideBarDocsAreaD__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSideBarDocsAreaD__ArgsType = {};
type ArgPropType = keyof PlasmicSideBarDocsAreaD__ArgsType;
export const PlasmicSideBarDocsAreaD__ArgProps = new Array<ArgPropType>();

export type PlasmicSideBarDocsAreaD__OverridesType = {
  root?: p.Flex<"div">;
  sideBarBookTitle?: p.Flex<typeof SideBarBookTitle>;
  list?: p.Flex<typeof DragListView>;
  addStock?: p.Flex<typeof AddStock>;
};

export interface DefaultSideBarDocsAreaDProps {
  className?: string;
}

function PlasmicSideBarDocsAreaD__RenderFunc(props: {
  variants: PlasmicSideBarDocsAreaD__VariantsArgs;
  args: PlasmicSideBarDocsAreaD__ArgsType;
  overrides: PlasmicSideBarDocsAreaD__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <SideBarBookTitle
          data-plasmic-name={"sideBarBookTitle"}
          data-plasmic-override={overrides.sideBarBookTitle}
          className={classNames("__wab_instance", sty.sideBarBookTitle)}
        />

        <DragListView
          data-plasmic-name={"list"}
          data-plasmic-override={overrides.list}
          className={classNames("__wab_instance", sty.list)}
        />

        {true ? (
          <AddStock
            data-plasmic-name={"addStock"}
            data-plasmic-override={overrides.addStock}
            className={classNames("__wab_instance", sty.addStock)}
          />
        ) : null}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "sideBarBookTitle", "list", "addStock"],
  sideBarBookTitle: ["sideBarBookTitle"],
  list: ["list"],
  addStock: ["addStock"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sideBarBookTitle: typeof SideBarBookTitle;
  list: typeof DragListView;
  addStock: typeof AddStock;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSideBarDocsAreaD__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSideBarDocsAreaD__VariantsArgs;
    args?: PlasmicSideBarDocsAreaD__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSideBarDocsAreaD__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSideBarDocsAreaD__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSideBarDocsAreaD__ArgProps,
      internalVariantPropNames: PlasmicSideBarDocsAreaD__VariantProps
    });

    return PlasmicSideBarDocsAreaD__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSideBarDocsAreaD";
  } else {
    func.displayName = `PlasmicSideBarDocsAreaD.${nodeName}`;
  }
  return func;
}

export const PlasmicSideBarDocsAreaD = Object.assign(
  // Top-level PlasmicSideBarDocsAreaD renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sideBarBookTitle: makeNodeComponent("sideBarBookTitle"),
    list: makeNodeComponent("list"),
    addStock: makeNodeComponent("addStock"),

    // Metadata about props expected for PlasmicSideBarDocsAreaD
    internalVariantProps: PlasmicSideBarDocsAreaD__VariantProps,
    internalArgProps: PlasmicSideBarDocsAreaD__ArgProps
  }
);

export default PlasmicSideBarDocsAreaD;
/* prettier-ignore-end */
