// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jRkyHyW5xUgunu5SjYQV4L
// Component: 1WJG8XuDtI
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import { LoggedInValue, useLoggedIn } from "./PlasmicGlobalVariant__LoggedIn"; // plasmic-import: VsyhYsfbuU/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_doc_bundle.module.css"; // plasmic-import: jRkyHyW5xUgunu5SjYQV4L/projectcss
import sty from "./PlasmicSideBarLogout.module.css"; // plasmic-import: 1WJG8XuDtI/css

import LogoutIcon from "./icons/PlasmicIcon__Logout"; // plasmic-import: S-Yq0rCjv/icon

export type PlasmicSideBarLogout__VariantMembers = {};

export type PlasmicSideBarLogout__VariantsArgs = {};
type VariantPropType = keyof PlasmicSideBarLogout__VariantsArgs;
export const PlasmicSideBarLogout__VariantProps = new Array<VariantPropType>();

export type PlasmicSideBarLogout__ArgsType = {};
type ArgPropType = keyof PlasmicSideBarLogout__ArgsType;
export const PlasmicSideBarLogout__ArgProps = new Array<ArgPropType>();

export type PlasmicSideBarLogout__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  text?: p.Flex<"div">;
};

export interface DefaultSideBarLogoutProps {
  className?: string;
}

function PlasmicSideBarLogout__RenderFunc(props: {
  variants: PlasmicSideBarLogout__VariantsArgs;
  args: PlasmicSideBarLogout__ArgsType;
  overrides: PlasmicSideBarLogout__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    loggedIn: useLoggedIn()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [projectcss.global_loggedIn__true]: hasVariant(
            globalVariants,
            "loggedIn",
            "_true"
          ),
          [sty.rootglobal_loggedIn__true]: hasVariant(
            globalVariants,
            "loggedIn",
            "_true"
          )
        }
      )}
    >
      <LogoutIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Log out"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSideBarLogout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSideBarLogout__VariantsArgs;
    args?: PlasmicSideBarLogout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSideBarLogout__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSideBarLogout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSideBarLogout__ArgProps,
      internalVariantPropNames: PlasmicSideBarLogout__VariantProps
    });

    return PlasmicSideBarLogout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSideBarLogout";
  } else {
    func.displayName = `PlasmicSideBarLogout.${nodeName}`;
  }
  return func;
}

export const PlasmicSideBarLogout = Object.assign(
  // Top-level PlasmicSideBarLogout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicSideBarLogout
    internalVariantProps: PlasmicSideBarLogout__VariantProps,
    internalArgProps: PlasmicSideBarLogout__ArgProps
  }
);

export default PlasmicSideBarLogout;
/* prettier-ignore-end */
