// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jRkyHyW5xUgunu5SjYQV4L
// Component: elLQBcgJLt
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_doc_bundle.module.css"; // plasmic-import: jRkyHyW5xUgunu5SjYQV4L/projectcss
import sty from "./PlasmicOverlay.module.css"; // plasmic-import: elLQBcgJLt/css

export type PlasmicOverlay__VariantMembers = {};

export type PlasmicOverlay__VariantsArgs = {};
type VariantPropType = keyof PlasmicOverlay__VariantsArgs;
export const PlasmicOverlay__VariantProps = new Array<VariantPropType>();

export type PlasmicOverlay__ArgsType = {
  modal?: React.ReactNode;
};

type ArgPropType = keyof PlasmicOverlay__ArgsType;
export const PlasmicOverlay__ArgProps = new Array<ArgPropType>("modal");

export type PlasmicOverlay__OverridesType = {
  root?: p.Flex<"div">;
  modal?: p.Flex<"div">;
};

export interface DefaultOverlayProps {
  modal?: React.ReactNode;
  className?: string;
}

function PlasmicOverlay__RenderFunc(props: {
  variants: PlasmicOverlay__VariantsArgs;
  args: PlasmicOverlay__ArgsType;
  overrides: PlasmicOverlay__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"modal"}
          data-plasmic-override={overrides.modal}
          className={classNames(projectcss.all, sty.modal)}
        >
          {p.renderPlasmicSlot({
            defaultContents: null,
            value: args.modal
          })}
        </div>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "modal"],
  modal: ["modal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  modal: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOverlay__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOverlay__VariantsArgs;
    args?: PlasmicOverlay__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOverlay__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicOverlay__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOverlay__ArgProps,
      internalVariantPropNames: PlasmicOverlay__VariantProps
    });

    return PlasmicOverlay__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOverlay";
  } else {
    func.displayName = `PlasmicOverlay.${nodeName}`;
  }
  return func;
}

export const PlasmicOverlay = Object.assign(
  // Top-level PlasmicOverlay renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    modal: makeNodeComponent("modal"),

    // Metadata about props expected for PlasmicOverlay
    internalVariantProps: PlasmicOverlay__VariantProps,
    internalArgProps: PlasmicOverlay__ArgProps
  }
);

export default PlasmicOverlay;
/* prettier-ignore-end */
