// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSideBarLogout,
  DefaultSideBarLogoutProps
} from "./plasmic/doc_bundle/PlasmicSideBarLogout";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { signIn, signOut } from "../utils/firebase/auth";


// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface SideBarLogoutProps extends Omit<DefaultSideBarLogoutProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultSideBarLogoutProps altogether and have
// total control over the props for your component.
export interface SideBarLogoutProps extends DefaultSideBarLogoutProps {}

function SideBarLogout_(
  props: SideBarLogoutProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicSideBarLogout to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSideBarLogout are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all SideBarLogoutProps here, but feel free
  // to do whatever works for you.

  return (
    <PlasmicSideBarLogout 
      root={{ ref }}
      onClick = {() => signOut()}
      {...props} 
    />
  );
}

const SideBarLogout = React.forwardRef(SideBarLogout_);
export default SideBarLogout;
