// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import firebase from "firebase/app";
import { useAuthState } from "../hooks/useAuthState";
import { signIn, signOut } from "../utils/firebase/auth";

import { PlasmicHomepage } from "../components/plasmic/doc_bundle/PlasmicHomepage";

function Homepage() {
  return (
    <>
      <PlasmicHomepage 
        docs={{
          render: () => null
        }}
      />
    </>
  );
}

export default Homepage;
